channels:
  - bioconda
  - conda-forge
dependencies:
  - matplotlib-base=3.9.4
  - numpy=2.0.2
  - openpyxl=3.1.5
  - pandas=2.3.1
  - python=3.9.23
  - pyyaml=6.0.2
  - seaborn=0.13.2
  - venn=0.1.3
  - yaml=0.2.5
