| Model                                                                                                                             | Toxin                     | Source   | FOLD                           |   Genomes | pdbs                                                                                                                                                                                                |
|:----------------------------------------------------------------------------------------------------------------------------------|:--------------------------|:---------|:-------------------------------|----------:|:----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| STox_21.1 [aln without gap](./html/STox_21.1.without_gaps.html) [aln](./html/STox_21.1.with_gaps.html)                            | STox_21                   | st       |                                |         2 | [view](https://molstar.org/viewer/?structure-url=https://ggnicastro.github.io/10k/alns/pdbs/STox_21.1.pdb&structure-url-format=pdb) [download](./alns/pdbs/STox_21.1.pdb)                   |
| STox_9.1 [aln without gap](./html/STox_9.1.without_gaps.html) [aln](./html/STox_9.1.with_gaps.html)                               | STox_9 (TreTu)            | st       | ADP-ribosyltransferase         |      1227 | [view](https://molstar.org/viewer/?structure-url=https://ggnicastro.github.io/10k/alns/pdbs/STox_9.1.pdb&structure-url-format=pdb) [download](./alns/pdbs/STox_9.1.pdb)                     |
| Tox-ART-HYD.1 [aln without gap](./html/Tox-ART-HYD.1.without_gaps.html) [aln](./html/Tox-ART-HYD.1.with_gaps.html)                | Tox-ART-HYD               | st       | ADP-ribosyltransferase         |        11 | [view](https://molstar.org/viewer/?structure-url=https://ggnicastro.github.io/10k/alns/pdbs/Tox-ART-HYD.1.pdb&structure-url-format=pdb) [download](./alns/pdbs/Tox-ART-HYD.1.pdb)           |
| Tox-ART-HYD.2 [aln without gap](./html/Tox-ART-HYD.2.without_gaps.html) [aln](./html/Tox-ART-HYD.2.with_gaps.html)                | Tox-ART-HYD               | st       | ADP-ribosyltransferase         |       186 | [view](https://molstar.org/viewer/?structure-url=https://ggnicastro.github.io/10k/alns/pdbs/Tox-ART-HYD.2.pdb&structure-url-format=pdb) [download](./alns/pdbs/Tox-ART-HYD.2.pdb)           |
| STox_12.1 [aln without gap](./html/STox_12.1.without_gaps.html) [aln](./html/STox_12.1.with_gaps.html)                            | STox_12 (Tox-ART)         | st       | ADP-ribosyltransferase         |         4 | [view](https://molstar.org/viewer/?structure-url=https://ggnicastro.github.io/10k/alns/pdbs/STox_12.1.pdb&structure-url-format=pdb) [download](./alns/pdbs/STox_12.1.pdb)                   |
| STox_28.1 [aln without gap](./html/STox_28.1.without_gaps.html) [aln](./html/STox_28.1.with_gaps.html)                            | STox_28 (RhsP2)           | st       | ADP-ribosyltransferase         |         5 | [view](https://molstar.org/viewer/?structure-url=https://ggnicastro.github.io/10k/alns/pdbs/STox_28.1.pdb&structure-url-format=pdb) [download](./alns/pdbs/STox_28.1.pdb)                   |
| CARP-ART.1 [aln without gap](./html/CARP-ART.1.without_gaps.html) [aln](./html/CARP-ART.1.with_gaps.html)                         | CARP-ART/Tox-ART-RSE      | st       | ADP-ribosyltransferase         |        49 | [view](https://molstar.org/viewer/?structure-url=https://ggnicastro.github.io/10k/alns/pdbs/CARP-ART.1.pdb&structure-url-format=pdb) [download](./alns/pdbs/CARP-ART.1.pdb)                 |
| STox_23.1 [aln without gap](./html/STox_23.1.without_gaps.html) [aln](./html/STox_23.1.with_gaps.html)                            | STox_23                   | st       | ADP-ribosyltransferase         |        26 | [view](https://molstar.org/viewer/?structure-url=https://ggnicastro.github.io/10k/alns/pdbs/STox_23.1.pdb&structure-url-format=pdb) [download](./alns/pdbs/STox_23.1.pdb)                   |
| STox_10.1 [aln without gap](./html/STox_10.1.without_gaps.html) [aln](./html/STox_10.1.with_gaps.html)                            | STox_10                   | st       | Adenylylcyclase toxin          |        20 | [view](https://molstar.org/viewer/?structure-url=https://ggnicastro.github.io/10k/alns/pdbs/STox_10.1.pdb&structure-url-format=pdb) [download](./alns/pdbs/STox_10.1.pdb)                   |
| Ntox44.1 [aln without gap](./html/Ntox44.1.without_gaps.html) [aln](./html/Ntox44.1.with_gaps.html)                               | Ntox44                    | st       | All alpha                      |        14 | [view](https://molstar.org/viewer/?structure-url=https://ggnicastro.github.io/10k/alns/pdbs/Ntox44.1.pdb&structure-url-format=pdb) [download](./alns/pdbs/Ntox44.1.pdb)                     |
| Ntox34.1 [aln without gap](./html/Ntox34.1.without_gaps.html) [aln](./html/Ntox34.1.with_gaps.html)                               | Ntox34                    | st       | All alpha                      |        26 | [view](https://molstar.org/viewer/?structure-url=https://ggnicastro.github.io/10k/alns/pdbs/Ntox34.1.pdb&structure-url-format=pdb) [download](./alns/pdbs/Ntox34.1.pdb)                     |
| Ntox44.2 [aln without gap](./html/Ntox44.2.without_gaps.html) [aln](./html/Ntox44.2.with_gaps.html)                               | Ntox44                    | st       | All alpha                      |        16 | [view](https://molstar.org/viewer/?structure-url=https://ggnicastro.github.io/10k/alns/pdbs/Ntox44.2.pdb&structure-url-format=pdb) [download](./alns/pdbs/Ntox44.2.pdb)                     |
| STox_18.1 [aln without gap](./html/STox_18.1.without_gaps.html) [aln](./html/STox_18.1.with_gaps.html)                            | Stox_18 (Gly-Zipper)      | st       | All-alpha                      |       223 | [view](https://molstar.org/viewer/?structure-url=https://ggnicastro.github.io/10k/alns/pdbs/STox_18.1.pdb&structure-url-format=pdb) [download](./alns/pdbs/STox_18.1.pdb)                   |
| Ntox19.1 [aln without gap](./html/Ntox19.1.without_gaps.html) [aln](./html/Ntox19.1.with_gaps.html)                               | Ntox19                    | st       | BECR                           |         9 | [view](https://molstar.org/viewer/?structure-url=https://ggnicastro.github.io/10k/alns/pdbs/Ntox19.1.pdb&structure-url-format=pdb) [download](./alns/pdbs/Ntox19.1.pdb)                     |
| Ntox49.1 [aln without gap](./html/Ntox49.1.without_gaps.html) [aln](./html/Ntox49.1.with_gaps.html)                               | Ntox49                    | st       | BECR                           |        49 | [view](https://molstar.org/viewer/?structure-url=https://ggnicastro.github.io/10k/alns/pdbs/Ntox49.1.pdb&structure-url-format=pdb) [download](./alns/pdbs/Ntox49.1.pdb)                     |
| Ntox_7.1 [aln without gap](./html/Ntox_7.1.without_gaps.html) [aln](./html/Ntox_7.1.with_gaps.html)                               | Ntox7                     | st       | BECR                           |         8 | [view](https://molstar.org/viewer/?structure-url=https://ggnicastro.github.io/10k/alns/pdbs/Ntox_7.1.pdb&structure-url-format=pdb) [download](./alns/pdbs/Ntox_7.1.pdb)                     |
| Tox-EndoU2.1 [aln without gap](./html/Tox-EndoU2.1.without_gaps.html) [aln](./html/Tox-EndoU2.1.with_gaps.html)                   | Tox-EndoU                 | st       | BECR                           |        39 | [view](https://molstar.org/viewer/?structure-url=https://ggnicastro.github.io/10k/alns/pdbs/Tox-EndoU2.1.pdb&structure-url-format=pdb) [download](./alns/pdbs/Tox-EndoU2.1.pdb)             |
| Ntox47.1 [aln without gap](./html/Ntox47.1.without_gaps.html) [aln](./html/Ntox47.1.with_gaps.html)                               | Ntox47                    | st       | BECR                           |      1898 | [view](https://molstar.org/viewer/?structure-url=https://ggnicastro.github.io/10k/alns/pdbs/Ntox47.1.pdb&structure-url-format=pdb) [download](./alns/pdbs/Ntox47.1.pdb)                     |
| Tox-HNH-EHHH.3 [aln without gap](./html/Tox-HNH-EHHH.3.without_gaps.html) [aln](./html/Tox-HNH-EHHH.3.with_gaps.html)             | Tox-HNH-EHHH              | st       | BECR/HNH                       |        23 | [view](https://molstar.org/viewer/?structure-url=https://ggnicastro.github.io/10k/alns/pdbs/Tox-HNH-EHHH.3.pdb&structure-url-format=pdb) [download](./alns/pdbs/Tox-HNH-EHHH.3.pdb)         |
| STox_1.1 [aln without gap](./html/STox_1.1.without_gaps.html) [aln](./html/STox_1.1.with_gaps.html)                               | Stox_1                    | st       | BECR/HNH                       |        11 | [view](https://molstar.org/viewer/?snapshot-url=https://ggnicastro.github.io/10k/alns/pdbs/STox_1.1.molx&snapshot-url-type=molx) [download](./alns/pdbs/STox_1.1.molx)                     |
| STox_5.1 [aln without gap](./html/STox_5.1.without_gaps.html) [aln](./html/STox_5.1.with_gaps.html)                               | STox_5 (CdiA PDB: 5T86)   | st       | BECR/HNH                       |      1579 | [view](https://molstar.org/viewer/?structure-url=https://ggnicastro.github.io/10k/alns/pdbs/STox_5.1.pdb&structure-url-format=pdb) [download](./alns/pdbs/STox_5.1.pdb)                     |
| STox_1.2 [aln without gap](./html/STox_1.2.without_gaps.html) [aln](./html/STox_1.2.with_gaps.html)                               | Stox_1                    | st       | BECR/HNH                       |         1 | [view](https://molstar.org/viewer/?structure-url=https://ggnicastro.github.io/10k/alns/pdbs/STox_1.2.pdb&structure-url-format=pdb) [download](./alns/pdbs/STox_1.2.pdb)                     |
| STox_2.1 [aln without gap](./html/STox_2.1.without_gaps.html) [aln](./html/STox_2.1.with_gaps.html)                               | Stox_2                    | st       | BECR/HNH                       |         1 | [view](https://molstar.org/viewer/?structure-url=https://ggnicastro.github.io/10k/alns/pdbs/STox_2.1.pdb&structure-url-format=pdb) [download](./alns/pdbs/STox_2.1.pdb)                     |
| Tox-HNH-EHHH.2 [aln without gap](./html/Tox-HNH-EHHH.2.without_gaps.html) [aln](./html/Tox-HNH-EHHH.2.with_gaps.html)             | Tox-HNH-EHHH              | st       | BECR/HNH                       |        47 | [view](https://molstar.org/viewer/?structure-url=https://ggnicastro.github.io/10k/alns/pdbs/Tox-HNH-EHHH.2.pdb&structure-url-format=pdb) [download](./alns/pdbs/Tox-HNH-EHHH.2.pdb)         |
| STox_4.1 [aln without gap](./html/STox_4.1.without_gaps.html) [aln](./html/STox_4.1.with_gaps.html)                               | STox_4                    | st       | BECR/HNH                       |        44 | [view](https://molstar.org/viewer/?structure-url=https://ggnicastro.github.io/10k/alns/pdbs/STox_4.1.pdb&structure-url-format=pdb) [download](./alns/pdbs/STox_4.1.pdb)                     |
| Tox-HNH-EHHH.1 [aln without gap](./html/Tox-HNH-EHHH.1.without_gaps.html) [aln](./html/Tox-HNH-EHHH.1.with_gaps.html)             | Tox-HNH-EHHH              | st       | BECR/HNH                       |        78 | [view](https://molstar.org/viewer/?structure-url=https://ggnicastro.github.io/10k/alns/pdbs/Tox-HNH-EHHH.1.pdb&structure-url-format=pdb) [download](./alns/pdbs/Tox-HNH-EHHH.1.pdb)         |
| STox_3.1 [aln without gap](./html/STox_3.1.without_gaps.html) [aln](./html/STox_3.1.with_gaps.html)                               | STox_3                    | st       | BECR/HNH                       |        63 | [view](https://molstar.org/viewer/?structure-url=https://ggnicastro.github.io/10k/alns/pdbs/STox_3.1.pdb&structure-url-format=pdb) [download](./alns/pdbs/STox_3.1.pdb)                     |
| STox_6.1 [aln without gap](./html/STox_6.1.without_gaps.html) [aln](./html/STox_6.1.with_gaps.html)                               | STox_6                    | st       | BECR/HNH                       |        13 | [view](https://molstar.org/viewer/?structure-url=https://ggnicastro.github.io/10k/alns/pdbs/STox_6.1.pdb&structure-url-format=pdb) [download](./alns/pdbs/STox_6.1.pdb)                     |
| Tae2.1 [aln without gap](./html/Tae2.1.without_gaps.html) [aln](./html/Tae2.1.with_gaps.html)                                     | Tae2                      | st       | CHAP                           |       744 | [view](https://molstar.org/viewer/?structure-url=https://ggnicastro.github.io/10k/alns/pdbs/Tae2.1.pdb&structure-url-format=pdb) [download](./alns/pdbs/Tae2.1.pdb)                         |
| Tox-Caspase.1 [aln without gap](./html/Tox-Caspase.1.without_gaps.html) [aln](./html/Tox-Caspase.1.with_gaps.html)                | Tox-Caspase               | st       | Caspase-like                   |       576 | [view](https://molstar.org/viewer/?structure-url=https://ggnicastro.github.io/10k/alns/pdbs/Tox-Caspase.1.pdb&structure-url-format=pdb) [download](./alns/pdbs/Tox-Caspase.1.pdb)           |
| Tox-Caspase.1 [aln without gap](./html/Tox-Caspase.1.without_gaps.html) [aln](./html/Tox-Caspase.1.with_gaps.html)                | Tox-Caspase               | aravind  | Caspase-like                   |        25 | [view](https://molstar.org/viewer/?structure-url=https://ggnicastro.github.io/10k/alns/pdbs/Tox-Caspase.1.pdb&structure-url-format=pdb) [download](./alns/pdbs/Tox-Caspase.1.pdb)           |
| STox_29.1 [aln without gap](./html/STox_29.1.without_gaps.html) [aln](./html/STox_29.1.with_gaps.html)                            | Stox_29                   | st       | Colicin D - CRD                |        13 | [view](https://molstar.org/viewer/?structure-url=https://ggnicastro.github.io/10k/alns/pdbs/STox_29.1.pdb&structure-url-format=pdb) [download](./alns/pdbs/STox_29.1.pdb)                   |
| STox_17.2 [aln without gap](./html/STox_17.2.without_gaps.html) [aln](./html/STox_17.2.with_gaps.html)                            | STox_17                   | st       | Colicin-like                   |        30 | [view](https://molstar.org/viewer/?structure-url=https://ggnicastro.github.io/10k/alns/pdbs/STox_17.2.pdb&structure-url-format=pdb) [download](./alns/pdbs/STox_17.2.pdb)                   |
| Tox-JAB.2 [aln without gap](./html/Tox-JAB.2.without_gaps.html) [aln](./html/Tox-JAB.2.with_gaps.html)                            | Tox-JAB2                  | st       | Deaminase, Deaminase-like fold |        18 | [view](https://molstar.org/viewer/?structure-url=https://ggnicastro.github.io/10k/alns/pdbs/Tox-JAB.2.pdb&structure-url-format=pdb) [download](./alns/pdbs/Tox-JAB.2.pdb)                   |
| Tox-JAB.1 [aln without gap](./html/Tox-JAB.1.without_gaps.html) [aln](./html/Tox-JAB.1.with_gaps.html)                            | Tox-JAB2                  | st       | Deaminase, Deaminase-like fold |         2 | [view](https://molstar.org/viewer/?structure-url=https://ggnicastro.github.io/10k/alns/pdbs/Tox-JAB.1.pdb&structure-url-format=pdb) [download](./alns/pdbs/Tox-JAB.1.pdb)                   |
| STox_20.1 [aln without gap](./html/STox_20.1.without_gaps.html) [aln](./html/STox_20.1.with_gaps.html)                            | STox_20                   | st       | Deaminase-like fold            |         3 | [view](https://molstar.org/viewer/?structure-url=https://ggnicastro.github.io/10k/alns/pdbs/STox_20.1.pdb&structure-url-format=pdb) [download](./alns/pdbs/STox_20.1.pdb)                   |
| Tox-AHH.2 [aln without gap](./html/Tox-AHH.2.without_gaps.html) [aln](./html/Tox-AHH.2.with_gaps.html)                            | Tox-AHH                   | aravind  | HNH/Endo VII (His-Me)          |         1 | [view](https://molstar.org/viewer/?structure-url=https://ggnicastro.github.io/10k/alns/pdbs/Tox-AHH.2.pdb&structure-url-format=pdb) [download](./alns/pdbs/Tox-AHH.2.pdb)                   |
| Tox-CompNuc.1 [aln without gap](./html/Tox-CompNuc.1.without_gaps.html) [aln](./html/Tox-CompNuc.1.with_gaps.html)                | Tox-CompNuc/Tox-NucA      | st       | HNH/Endo VII (His-Me)          |        25 | [view](https://molstar.org/viewer/?structure-url=https://ggnicastro.github.io/10k/alns/pdbs/Tox-CompNuc.1.pdb&structure-url-format=pdb) [download](./alns/pdbs/Tox-CompNuc.1.pdb)           |
| Tox-AHH.1 [aln without gap](./html/Tox-AHH.1.without_gaps.html) [aln](./html/Tox-AHH.1.with_gaps.html)                            | Tox-AHH                   | st       | HNH/Endo VII (His-Me)          |         3 | [view](https://molstar.org/viewer/?structure-url=https://ggnicastro.github.io/10k/alns/pdbs/Tox-AHH.1.pdb&structure-url-format=pdb) [download](./alns/pdbs/Tox-AHH.1.pdb)                   |
| Ntox18.1 [aln without gap](./html/Ntox18.1.without_gaps.html) [aln](./html/Ntox18.1.with_gaps.html)                               | Ntox18                    | st       | HNH/Endo VII (His-Me)          |        33 | [view](https://molstar.org/viewer/?structure-url=https://ggnicastro.github.io/10k/alns/pdbs/Ntox18.1.pdb&structure-url-format=pdb) [download](./alns/pdbs/Ntox18.1.pdb)                     |
| STox_36.1 [aln without gap](./html/STox_36.1.without_gaps.html) [aln](./html/STox_36.1.with_gaps.html)                            | STox_36 (ColE7)           | st       | HNH/Endo VII (His-Me)          |       114 | [view](https://molstar.org/viewer/?structure-url=https://ggnicastro.github.io/10k/alns/pdbs/STox_36.1.pdb&structure-url-format=pdb) [download](./alns/pdbs/STox_36.1.pdb)                   |
| Tox-AHH.2 [aln without gap](./html/Tox-AHH.2.without_gaps.html) [aln](./html/Tox-AHH.2.with_gaps.html)                            | Tox-AHH                   | st       | HNH/Endo VII (His-Me)          |        75 | [view](https://molstar.org/viewer/?structure-url=https://ggnicastro.github.io/10k/alns/pdbs/Tox-AHH.2.pdb&structure-url-format=pdb) [download](./alns/pdbs/Tox-AHH.2.pdb)                   |
| Tox-WHH.2 [aln without gap](./html/Tox-WHH.2.without_gaps.html) [aln](./html/Tox-WHH.2.with_gaps.html)                            | Tox-WHH                   | st       | HNH/Endo VII (His-Me)          |        32 | [view](https://molstar.org/viewer/?structure-url=https://ggnicastro.github.io/10k/alns/pdbs/Tox-WHH.2.pdb&structure-url-format=pdb) [download](./alns/pdbs/Tox-WHH.2.pdb)                   |
| Ntox18.2 [aln without gap](./html/Ntox18.2.without_gaps.html) [aln](./html/Ntox18.2.with_gaps.html)                               | Ntox18                    | st       | HNH/Endo VII (His-Me)          |         1 | [view](https://molstar.org/viewer/?structure-url=https://ggnicastro.github.io/10k/alns/pdbs/Ntox18.2.pdb&structure-url-format=pdb) [download](./alns/pdbs/Ntox18.2.pdb)                     |
| Tox-WHH.1 [aln without gap](./html/Tox-WHH.1.without_gaps.html) [aln](./html/Tox-WHH.1.with_gaps.html)                            | Tox-WHH                   | st       | HNH/Endo VII (His-Me)          |       304 | [view](https://molstar.org/viewer/?structure-url=https://ggnicastro.github.io/10k/alns/pdbs/Tox-WHH.1.pdb&structure-url-format=pdb) [download](./alns/pdbs/Tox-WHH.1.pdb)                   |
| Tox-AHH.3 [aln without gap](./html/Tox-AHH.3.without_gaps.html) [aln](./html/Tox-AHH.3.with_gaps.html)                            | Tox-AHH                   | st       | HNH/Endo VII (His-Me)          |         1 | [view](https://molstar.org/viewer/?structure-url=https://ggnicastro.github.io/10k/alns/pdbs/Tox-AHH.3.pdb&structure-url-format=pdb) [download](./alns/pdbs/Tox-AHH.3.pdb)                   |
| HNHGH-E.1 [aln without gap](./html/HNHGH-E.1.without_gaps.html) [aln](./html/HNHGH-E.1.with_gaps.html)                            | HNHGH-E                   | st       | HNH/Endo VII (His-Me)          |         4 | [view](https://molstar.org/viewer/?structure-url=https://ggnicastro.github.io/10k/alns/pdbs/HNHGH-E.1.pdb&structure-url-format=pdb) [download](./alns/pdbs/HNHGH-E.1.pdb)                   |
| Tox-WHH.2 [aln without gap](./html/Tox-WHH.2.without_gaps.html) [aln](./html/Tox-WHH.2.with_gaps.html)                            | Tox-WHH                   | aravind  | HNH/Endo VII (His-Me)          |         1 | [view](https://molstar.org/viewer/?structure-url=https://ggnicastro.github.io/10k/alns/pdbs/Tox-WHH.2.pdb&structure-url-format=pdb) [download](./alns/pdbs/Tox-WHH.2.pdb)                   |
| Tox-AHH.4 [aln without gap](./html/Tox-AHH.4.without_gaps.html) [aln](./html/Tox-AHH.4.with_gaps.html)                            | Tox-AHH                   | st       | HNH/Endo VII (His-Me)          |        12 | [view](https://molstar.org/viewer/?structure-url=https://ggnicastro.github.io/10k/alns/pdbs/Tox-AHH.4.pdb&structure-url-format=pdb) [download](./alns/pdbs/Tox-AHH.4.pdb)                   |
| STox_26.1 [aln without gap](./html/STox_26.1.without_gaps.html) [aln](./html/STox_26.1.with_gaps.html)                            | STox_26 (Tox-HNH-LHH)     | st       | HNH/Endo VII (His-Me)          |        61 | [view](https://molstar.org/viewer/?structure-url=https://ggnicastro.github.io/10k/alns/pdbs/STox_26.1.pdb&structure-url-format=pdb) [download](./alns/pdbs/STox_26.1.pdb)                   |
| SImm_04012 [aln without gap](./html/SImm_04012.without_gaps.html) [aln](./html/SImm_04012.with_gaps.html)                         | SImm_04012                | st       | Immunity Protein               |        96 | [view](https://molstar.org/viewer/?structure-url=https://ggnicastro.github.io/10k/alns/pdbs/SImm_04012.pdb&structure-url-format=pdb) [download](./alns/pdbs/SImm_04012.pdb)                 |
| Tlde1.2 [aln without gap](./html/Tlde1.2.without_gaps.html) [aln](./html/Tlde1.2.with_gaps.html)                                  | Tlde1                     | st       | LD-Peptidase                   |        32 | [view](https://molstar.org/viewer/?structure-url=https://ggnicastro.github.io/10k/alns/pdbs/Tlde1.2.pdb&structure-url-format=pdb) [download](./alns/pdbs/Tlde1.2.pdb)                       |
| Tlde1.1 [aln without gap](./html/Tlde1.1.without_gaps.html) [aln](./html/Tlde1.1.with_gaps.html)                                  | Tlde1                     | st       | LD-Peptidase                   |      5018 | [view](https://molstar.org/viewer/?structure-url=https://ggnicastro.github.io/10k/alns/pdbs/Tlde1.1.pdb&structure-url-format=pdb) [download](./alns/pdbs/Tlde1.1.pdb)                       |
| Glucosaminidase.1 [aln without gap](./html/Glucosaminidase.1.without_gaps.html) [aln](./html/Glucosaminidase.1.with_gaps.html)    | Glucosaminidase           | aravind  | Lysozyme-like                  |      6160 | [view](https://molstar.org/viewer/?structure-url=https://ggnicastro.github.io/10k/alns/pdbs/Glucosaminidase.1.pdb&structure-url-format=pdb) [download](./alns/pdbs/Glucosaminidase.1.pdb)   |
| Glucosaminidase.1 [aln without gap](./html/Glucosaminidase.1.without_gaps.html) [aln](./html/Glucosaminidase.1.with_gaps.html)    | Glucosaminidase (Tge2PP)  | st       | Lysozyme-like                  |      6168 | [view](https://molstar.org/viewer/?structure-url=https://ggnicastro.github.io/10k/alns/pdbs/Glucosaminidase.1.pdb&structure-url-format=pdb) [download](./alns/pdbs/Glucosaminidase.1.pdb)   |
| STox_22.1 [aln without gap](./html/STox_22.1.without_gaps.html) [aln](./html/STox_22.1.with_gaps.html)                            | STox_22 (Tge2PP)          | st       | Lysozyme-like                  |        12 | [view](https://molstar.org/viewer/?structure-url=https://ggnicastro.github.io/10k/alns/pdbs/STox_22.1.pdb&structure-url-format=pdb) [download](./alns/pdbs/STox_22.1.pdb)                   |
| Lysozyme.1 [aln without gap](./html/Lysozyme.1.without_gaps.html) [aln](./html/Lysozyme.1.with_gaps.html)                         | Lysozyme/SLT              | st       | Lysozyme-like                  |      6199 | [view](https://molstar.org/viewer/?structure-url=https://ggnicastro.github.io/10k/alns/pdbs/Lysozyme.1.pdb&structure-url-format=pdb) [download](./alns/pdbs/Lysozyme.1.pdb)                 |
| Tox-HopH.1 [aln without gap](./html/Tox-HopH.1.without_gaps.html) [aln](./html/Tox-HopH.1.with_gaps.html)                         | Tox-HopH1                 | st       | Metallopeptidase               |      1640 | [view](https://molstar.org/viewer/?structure-url=https://ggnicastro.github.io/10k/alns/pdbs/Tox-HopH.1.pdb&structure-url-format=pdb) [download](./alns/pdbs/Tox-HopH.1.pdb)                 |
| Peptidase_M4.1 [aln without gap](./html/Peptidase_M4.1.without_gaps.html) [aln](./html/Peptidase_M4.1.with_gaps.html)             | Peptidase M4              | st       | Metallopeptidase               |        41 | [view](https://molstar.org/viewer/?structure-url=https://ggnicastro.github.io/10k/alns/pdbs/Peptidase_M4.1.pdb&structure-url-format=pdb) [download](./alns/pdbs/Peptidase_M4.1.pdb)         |
| Peptidase_M23.1 [aln without gap](./html/Peptidase_M23.1.without_gaps.html) [aln](./html/Peptidase_M23.1.with_gaps.html)          | Peptidase_M23             | st       | Metallopeptidase               |      6199 | [view](https://molstar.org/viewer/?structure-url=https://ggnicastro.github.io/10k/alns/pdbs/Peptidase_M23.1.pdb&structure-url-format=pdb) [download](./alns/pdbs/Peptidase_M23.1.pdb)       |
| STox_16.1 [aln without gap](./html/STox_16.1.without_gaps.html) [aln](./html/STox_16.1.with_gaps.html)                            | STox_16                   | st       | Papain-like peptidase          |        15 | [view](https://molstar.org/viewer/?structure-url=https://ggnicastro.github.io/10k/alns/pdbs/STox_16.1.pdb&structure-url-format=pdb) [download](./alns/pdbs/STox_16.1.pdb)                   |
| STox_15.1 [aln without gap](./html/STox_15.1.without_gaps.html) [aln](./html/STox_15.1.with_gaps.html)                            | STox_15                   | st       | Papain-like peptidase          |       401 | [view](https://molstar.org/viewer/?structure-url=https://ggnicastro.github.io/10k/alns/pdbs/STox_15.1.pdb&structure-url-format=pdb) [download](./alns/pdbs/STox_15.1.pdb)                   |
| ParBL.1 [aln without gap](./html/ParBL.1.without_gaps.html) [aln](./html/ParBL.1.with_gaps.html)                                  | Tox-ParBL1                | st       | ParB/Sulfiredoxin              |        14 | [view](https://molstar.org/viewer/?structure-url=https://ggnicastro.github.io/10k/alns/pdbs/ParBL.1.pdb&structure-url-format=pdb) [download](./alns/pdbs/ParBL.1.pdb)                       |
| ParBL.4 [aln without gap](./html/ParBL.4.without_gaps.html) [aln](./html/ParBL.4.with_gaps.html)                                  | Tox-ParBL1                | st       | ParB/Sulfiredoxin              |       103 | [view](https://molstar.org/viewer/?structure-url=https://ggnicastro.github.io/10k/alns/pdbs/ParBL.4.pdb&structure-url-format=pdb) [download](./alns/pdbs/ParBL.4.pdb)                       |
| ParBL.2 [aln without gap](./html/ParBL.2.without_gaps.html) [aln](./html/ParBL.2.with_gaps.html)                                  | Tox-ParBL1                | st       | ParB/Sulfiredoxin              |        28 | [view](https://molstar.org/viewer/?structure-url=https://ggnicastro.github.io/10k/alns/pdbs/ParBL.2.pdb&structure-url-format=pdb) [download](./alns/pdbs/ParBL.2.pdb)                       |
| Tae4.1 [aln without gap](./html/Tae4.1.without_gaps.html) [aln](./html/Tae4.1.with_gaps.html)                                     | Tae4                      | st       | Peptidase_CA                   |      3940 | [view](https://molstar.org/viewer/?structure-url=https://ggnicastro.github.io/10k/alns/pdbs/Tae4.1.pdb&structure-url-format=pdb) [download](./alns/pdbs/Tae4.1.pdb)                         |
| STox_27.1 [aln without gap](./html/STox_27.1.without_gaps.html) [aln](./html/STox_27.1.with_gaps.html)                            | STox_27 (Tle3 C-terminal) | st       | Phospholipase                  |         1 | [view](https://molstar.org/viewer/?structure-url=https://ggnicastro.github.io/10k/alns/pdbs/STox_27.1.pdb&structure-url-format=pdb) [download](./alns/pdbs/STox_27.1.pdb)                   |
| REase-7.1 [aln without gap](./html/REase-7.1.without_gaps.html) [aln](./html/REase-7.1.with_gaps.html)                            | Tox-REase-7               | st       | REase                          |         4 | [view](https://molstar.org/viewer/?structure-url=https://ggnicastro.github.io/10k/alns/pdbs/REase-7.1.pdb&structure-url-format=pdb) [download](./alns/pdbs/REase-7.1.pdb)                   |
| REase-3.1 [aln without gap](./html/REase-3.1.without_gaps.html) [aln](./html/REase-3.1.with_gaps.html)                            | Tox-Rease-3/4             | st       | REase                          |      6121 | [view](https://molstar.org/viewer/?structure-url=https://ggnicastro.github.io/10k/alns/pdbs/REase-3.1.pdb&structure-url-format=pdb) [download](./alns/pdbs/REase-3.1.pdb)                   |
| STox_30.1 [aln without gap](./html/STox_30.1.without_gaps.html) [aln](./html/STox_30.1.with_gaps.html)                            | STox_30                   | st       | REase                          |         1 | [view](https://molstar.org/viewer/?structure-url=https://ggnicastro.github.io/10k/alns/pdbs/STox_30.1.pdb&structure-url-format=pdb) [download](./alns/pdbs/STox_30.1.pdb)                   |
| Tox-Ribonuclease.1 [aln without gap](./html/Tox-Ribonuclease.1.without_gaps.html) [aln](./html/Tox-Ribonuclease.1.with_gaps.html) | Tox-Ribonuclease          | st       | Ribonuclease                   |        12 | [view](https://molstar.org/viewer/?structure-url=https://ggnicastro.github.io/10k/alns/pdbs/Tox-Ribonuclease.1.pdb&structure-url-format=pdb) [download](./alns/pdbs/Tox-Ribonuclease.1.pdb) |
| STox_14.1 [aln without gap](./html/STox_14.1.without_gaps.html) [aln](./html/STox_14.1.with_gaps.html)                            | STox_14                   | st       | Ribonuclease A                 |        33 | [view](https://molstar.org/viewer/?structure-url=https://ggnicastro.github.io/10k/alns/pdbs/STox_14.1.pdb&structure-url-format=pdb) [download](./alns/pdbs/STox_14.1.pdb)                   |
| Tox-URI1.1 [aln without gap](./html/Tox-URI1.1.without_gaps.html) [aln](./html/Tox-URI1.1.with_gaps.html)                         | Tox-URI                   | st       | URI nuclease                   |         2 | [view](https://molstar.org/viewer/?structure-url=https://ggnicastro.github.io/10k/alns/pdbs/Tox-URI1.1.pdb&structure-url-format=pdb) [download](./alns/pdbs/Tox-URI1.1.pdb)                 |
| Tox-URI2.1 [aln without gap](./html/Tox-URI2.1.without_gaps.html) [aln](./html/Tox-URI2.1.with_gaps.html)                         | Tox-URI                   | st       | URI nuclease                   |         3 | [view](https://molstar.org/viewer/?structure-url=https://ggnicastro.github.io/10k/alns/pdbs/Tox-URI2.1.pdb&structure-url-format=pdb) [download](./alns/pdbs/Tox-URI2.1.pdb)                 |
| Tox-URI2.1 [aln without gap](./html/Tox-URI2.1.without_gaps.html) [aln](./html/Tox-URI2.1.with_gaps.html)                         | Tox-URI                   | aravind  | URI nuclease                   |         4 | [view](https://molstar.org/viewer/?structure-url=https://ggnicastro.github.io/10k/alns/pdbs/Tox-URI2.1.pdb&structure-url-format=pdb) [download](./alns/pdbs/Tox-URI2.1.pdb)                 |
| STox_7.1 [aln without gap](./html/STox_7.1.without_gaps.html) [aln](./html/STox_7.1.with_gaps.html)                               | Tox-URI                   | st       | URI nuclease                   |        68 | [view](https://molstar.org/viewer/?structure-url=https://ggnicastro.github.io/10k/alns/pdbs/STox_7.1.pdb&structure-url-format=pdb) [download](./alns/pdbs/STox_7.1.pdb)                     |
| STox_33.1 [aln without gap](./html/STox_33.1.without_gaps.html) [aln](./html/STox_33.1.with_gaps.html)                            | STox_33                   | st       | Wnt?                           |         7 | [view](https://molstar.org/viewer/?structure-url=https://ggnicastro.github.io/10k/alns/pdbs/STox_33.1.pdb&structure-url-format=pdb) [download](./alns/pdbs/STox_33.1.pdb)                   |
| STox_19.1 [aln without gap](./html/STox_19.1.without_gaps.html) [aln](./html/STox_19.1.with_gaps.html)                            | STox_19                   | st       | Zincin-like                    |       164 | [view](https://molstar.org/viewer/?structure-url=https://ggnicastro.github.io/10k/alns/pdbs/STox_19.1.pdb&structure-url-format=pdb) [download](./alns/pdbs/STox_19.1.pdb)                   |
| STox_8 [aln without gap](./html/STox_8.without_gaps.html) [aln](./html/STox_8.with_gaps.html)                                     | STox_8 (Tle1)             | st       | a/b hydrolase                  |        83 | [view](https://molstar.org/viewer/?structure-url=https://ggnicastro.github.io/10k/alns/pdbs/STox_8.pdb&structure-url-format=pdb) [download](./alns/pdbs/STox_8.pdb)                         |
| STox_32.1 [aln without gap](./html/STox_32.1.without_gaps.html) [aln](./html/STox_32.1.with_gaps.html)                            | STox_32                   | st       | ppGpp synthase?                |        18 | [view](https://molstar.org/viewer/?structure-url=https://ggnicastro.github.io/10k/alns/pdbs/STox_32.1.pdb&structure-url-format=pdb) [download](./alns/pdbs/STox_32.1.pdb)                   |
| STox_34.1 [aln without gap](./html/STox_34.1.without_gaps.html) [aln](./html/STox_34.1.with_gaps.html)                            | STox_34                   | st       | nan                            |      1139 | [view](https://molstar.org/viewer/?structure-url=https://ggnicastro.github.io/10k/alns/pdbs/STox_34.1.pdb&structure-url-format=pdb) [download](./alns/pdbs/STox_34.1.pdb)                   |
| STox_25.1 [aln without gap](./html/STox_25.1.without_gaps.html) [aln](./html/STox_25.1.with_gaps.html)                            | STox_25                   | st       | nan                            |        81 | [view](https://molstar.org/viewer/?structure-url=https://ggnicastro.github.io/10k/alns/pdbs/STox_25.1.pdb&structure-url-format=pdb) [download](./alns/pdbs/STox_25.1.pdb)                   |
| STox_11.1 [aln without gap](./html/STox_11.1.without_gaps.html) [aln](./html/STox_11.1.with_gaps.html)                            | STox_11 (Similar to HicA) | st       | nan                            |         8 | [view](https://molstar.org/viewer/?structure-url=https://ggnicastro.github.io/10k/alns/pdbs/STox_11.1.pdb&structure-url-format=pdb) [download](./alns/pdbs/STox_11.1.pdb)                   |
| STox_24.1 [aln without gap](./html/STox_24.1.without_gaps.html) [aln](./html/STox_24.1.with_gaps.html)                            | STox_24                   | st       | nan                            |        23 | [view](https://molstar.org/viewer/?structure-url=https://ggnicastro.github.io/10k/alns/pdbs/STox_24.1.pdb&structure-url-format=pdb) [download](./alns/pdbs/STox_24.1.pdb)                   |
| STox_31.1 [aln without gap](./html/STox_31.1.without_gaps.html) [aln](./html/STox_31.1.with_gaps.html)                            | STox_31                   | st       | nan                            |       106 | [view](https://molstar.org/viewer/?structure-url=https://ggnicastro.github.io/10k/alns/pdbs/STox_31.1.pdb&structure-url-format=pdb) [download](./alns/pdbs/STox_31.1.pdb)                   |
| NAGPA.1 [aln without gap](./html/NAGPA.1.without_gaps.html) [aln](./html/NAGPA.1.with_gaps.html)                                  | STox_35 (NAGPA)           | st       | nan                            |         3 | [view](https://molstar.org/viewer/?structure-url=https://ggnicastro.github.io/10k/alns/pdbs/NAGPA.1.pdb&structure-url-format=pdb) [download](./alns/pdbs/NAGPA.1.pdb)                       |
